language: c
dist: trusty
install:
    - ./.travis/install_compiler.sh
    - git clone https://github.com/quiet/libfec.git && cd libfec && ./configure && make && sudo make install
    - git clone https://github.com/quiet/liquid-dsp.git -b devel --single-branch && cd liquid-dsp && aclocal -I./scripts && autoconf && autoheader && ./configure && make && sudo make install
    - wget http://www.digip.org/jansson/releases/jansson-2.7.tar.gz && tar -xzvf jansson-2.7.tar.gz && cd jansson-2.7 && ./configure && make && sudo make install
    - wget http://www.portaudio.com/archives/pa_stable_v19_20140130.tgz && tar -xzvf pa_stable_v19_20140130.tgz && cd portaudio && ./configure && make && sudo make install
    - wget http://www.mega-nerd.com/libsndfile/files/libsndfile-1.0.27.tar.gz && tar -xzvf libsndfile-1.0.27.tar.gz && cd libsndfile-1.0.27 && ./configure && make && sudo make install
    - sudo ldconfig
    - sudo usermod -a -G audio travis
    - sudo modprobe snd-aloop index=1 pcm_substreams=1
    - cd $TRAVIS_BUILD_DIR && cp ./.travis/.asoundrc ~/.asoundrc
    - sudo alsa force-reload
script:
    - cd $TRAVIS_BUILD_DIR && ./bootstrap
    - cd build && make check CTEST_OUTPUT_ON_FAILURE=TRUE
    - make programs && sudo make install
    - cd ..
    - sg audio -c "quiet_decode_soundcard audible README.md.soundcard &"
    - sg audio -c "quiet_encode_soundcard audible README.md"
    - sleep 6
    - killall quiet_decode_soundcard
    - sleep 1
    - quiet_encode_file audible README.md
    - quiet_decode_file audible README.md.file
    - diff --from-file=README.md README.md.soundcard README.md.file
